version: "3"

services:
  db:
    image: mysql:5.7
    volumes:
      - .data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: sample
      MYSQL_DATABASE: dpm
      MYSQL_USER: root

