version: "3"

services:
  db:
    image: mysql:5.7
    volumes:
      - .data:/var/lib/mysql
      - ./sql-init.sql:/sql-init.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: sample
      MYSQL_DATABASE: spm
      MYSQL_USER: root

