create table if not exists spm (
	id bigint(20) NOT NULL AUTO_INCREMENT,
	loginid varchar(255),
	companycode varchar(255),
	scrollid varchar(255),
	ssokid varchar(255),
	framecode varchar(255),
	processcode varchar(255),
	operationname varchar(255),
	operationdate datetime,
	contentsid varchar(255),
	contentsname varchar(255),
	devicecode varchar(255),
	deviceid varchar(255),
	memo_text text,
	page_no int(11),
	bookpage_no int(11),
	before_time datetime,
	after_time datetime,
	display int(11),
	page_row int(11),
	scale int(11),
	start_line int(11),
	end_line int(11),
	download_number int(11),
	time int(11),
	all_lines int(11),
	pages int(11),
	description mediumtext,
	import_date datetime,
	diftime bigint(20),
	cabinetid varchar(255),
	color varchar(255),
	markertext text,
	type varchar(255),
	positiontype varchar(255),
	chapter bigint(20),
	section bigint(20),
	subsection bigint(20),
	title varchar(255),
	text varchar(255),
	created_at datetime,
	updated_at datetime,
	course_id varchar(255),
	course_label text,
	course_title text,
	consumer_key varchar(255),
	contents_url varchar(255),
	systemHomePage varchar(255),
	version int(11),
	memo_hand text,
	memo_hand_bg tinyint(1),

	PRIMARY KEY (id)
)
